fix 4129-timeline-mute-is-now-inversed-to-be-play-sound
Bforartists/Bforartists pull request #4132
Opened 2024-03-10 01:04 UTC by Blenux

-- Changed the Mute audio checkbox to off by default, so users don't wonder why strips audio ain't playing sound.
-- Updated Description to match checkbox.

2024-03-10 02:42 UTC, iyadahmed commented
Sadly we should use invert checkbox instead
https://docs.blender.org/api/current/bpy.types.UILayout.html#bpy.types.UILayout.prop
![image](https://github.com/Bforartists/Bforartists/assets/25552173/1aeca372-53f2-4c41-851f-004643bcc8c2)

2024-03-10 02:49 UTC, iyadahmed requested changes
Sadly we should use invert checkbox instead
https://docs.blender.org/api/current/bpy.types.UILayout.html#bpy.types.UILayout.prop
![image](https://github.com/Bforartists/Bforartists/assets/25552173/1aeca372-53f2-4c41-851f-004643bcc8c2)

2024-03-11 01:10 UTC, Blenux commented
bah overthinked it :grin:

2024-03-11 04:52 UTC, Blenux commented
updated

2024-03-11 05:40 UTC, iyadahmed commented
I'm sorry I suggested invert checkbox, invert checkbox is just a UI thing it doesn't make audio play by default, and also changing Blender behavior is not right either, the correct solution is to change the default value, this is what the intent is from what is written in the original PR,

so in short,
let's change the default value,
but not the logic nor invert checkbox nor change description, because changing description will make the description not describe what the option does in reality,
Let's please pause work on this, until we all figure out and agree on this

2024-03-11 20:54 UTC, Blenux commented
All good mate, will wait till when ready :smiley: 

How does one change the default value without changing the logic, though?

2024-03-12 07:59 UTC, ReinerBforartists commented
Wouldn't be the correct solution to adopt to the Blender solution? They changed it. And i don't see any benefit in keeping our solution different. Just more confusion at the user side.

2024-03-12 12:42 UTC, iyadahmed commented
> Wouldn't be the correct solution to adopt to the Blender solution? They changed it. And i don't see any benefit in keeping our solution different. Just more confusion at the user side.

This is right, and I think our code already matched Blender for this functionality, the pull request was going to make bfa different than Blender and probably confuse people, and also addons that rely on this property, and also loading Blender files

2024-03-20 22:08 UTC, Draise14 commented
Gonna close this one and change the label with another commit. KISS

2024-03-20 22:08 UTC, closed without merging